shellEmulator: true

trustPolicy: no-downgrade

packages:
  - jetv-ui
overrides:
  '@electron/node-gyp': git+https://github.com/electron/node-gyp.git
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - lzma-native
  - oxc-resolver
  - simple-git-hooks
