name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # Install pnpm
      - name: Install pnpm
        run: corepack enable

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Build the project
      - name: Build the project
        run: pnpm build
