name: Build Project

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      # Changes involving the following path files will not trigger the workflow
      # 涉及以下路径文件的更改不会触发工作流
      - LICENSE
      - README.md
      - docs/**

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      # Changes involving the following path files will not trigger the workflow
      # 涉及以下路径文件的更改不会触发工作流
      - LICENSE
      - README.md
      - docs/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        node: [lts/*, lts/-1]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Update /JetV-ui
        run: pnpm update jetv-ui

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck

      - name: Build the project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm build

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: |
            build/*Setup*.exe
            build/*.dmg
            build/*.AppImage
          if: startsWith(matrix.os, 'windows') || startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
